name: "Lint and build frontend - PR"

on:
  pull_request:
    branches:
      - "main"
jobs:
  lint_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - name: install
        run: npm ci
        working-directory: ./
      - name: build
        run: npm run build
        working-directory: ./
      - name: lint
        run: npm run lint
        working-directory: ./
